### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by o5** [o5/grido#107]
**BUGS:**
- [x] <del>Filters\Text: Add DISTINCT to suggestion SELECT (#100)</del> [Released in 1.0.6]

**FEATURES:**
- [x] Name of some method refactoring (#98)
- [x] Inline editing (#70)
- [ ] <del>Modal editing?</del> [Maybe in future]
- [ ] <del>Column summarization?</del>  (#57) [Maybe in future]
