### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by o5** [o5/grido#71]
**TODO:**
- [x] ~~přepsat sestavování condition ve Filtru - https://github.com/o5/grido/commit/930d9d7e65a314ef9f93664cb7fbb90fb1875ac9 **[BC BREAK!]**~~
- [x] ~~dopsat testy - https://github.com/o5/grido/issues/13~~
- [x] ~~performance - https://github.com/o5/grido/commit/09bba986344d3a339b06422e6aff3c5ad110c1b4 a https://github.com/o5/grido/commit/1dd30b03499918c10b892016c1ffa70f87a9e72e~~
- [x] ~~odstranit ArrayObjectAccessor::hasProperty() - https://github.com/o5/grido/pull/43~~
- [x] ~~překlopit tests větev do mastera~~
- [x] ~~přesunutí závislostí na twitter bootstrap do šablony - https://github.com/o5/grido/pull/72~~
- [x] ~~projít bugy v issues a opravit co je možné~~
- [x] ~~**RELEASE: 0.9.3** - (verze **s** E_USER_DEPRECATED)~~
- [x] ~~odstranění deprecated věcí - "doklopení" z větve dev~~
- [x] ~~**RELEASE: 1.0.0** (verze **bez** E_USER_DEPRECATED)~~
- [x] ~~opravit / doplnit dokumentaci~~

**FEATURES:**
- [ ] modal editace
- [ ] SUM u sloupců (https://github.com/o5/grido/issues/57)
- [ ] vylepšení modelů (mám něco v hlavě :) )
- [ ] DI via \Nette\Config\CompilerExtension

**TASKS**:
~~1. Verzi (současný tests) s E_USER_DEPRECATED hodit jako 0.9.2?~~
~~2. Nějaké další návrhy na přejmenování metod / tříd / BC BREAKY?~~
~~3. Připomínky?~~
